server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zfx.cloud.entities              # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件

spring:
  application:
    name: zfx-cloud-provider-8001                           #微服务注册名配置说明
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=true             # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka          #单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      #集群版
  instance:
    instance-id: zfx-cloud-provider-8002   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:                                     #actuator与注册微服务info信息完善
  app.name: demo-zfx-cloud                #app的名字 可随意
  company.name: www.zfxcloud.com          #公司名字
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


 
 

